all:
	rm -rf mesage_client
	gcc -g  ../common/g_core.h ../common/g_util.h ../common/g_util.c ../ini/ini.h ../ini/ini.c message_client.h message_client.c -o message_client
clean:
	rm -rf message_client
